import React, { useState, useEffect, useRef } from 'react';
import BoqTable from '../components/BoqTable.jsx';
import PrimaryButton from '../components/PrimaryButton.jsx';

/**
 * PhaseBoq — unified Plan + Actual BOQ phase component.
 *
 * Phases:
 *  'plan'   → engineer fills Plan Measurement + Plan BOQ, then submits
 *  'actual' → Plan section becomes read-only; engineer fills Actual
 *             Measurement + Final BOQ (pre-filled from plan), then submits
 *
 * PDF export renders a hidden printable div and calls window.print().
 * The print stylesheet (boq-print.css) hides everything except .boq-print-area.
 */

/* ─────────────────── helpers ─────────────────── */
const fmt = (n) =>
  `₱${(parseFloat(n) || 0).toLocaleString('en-PH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const grandTotal = (rows = []) =>
  rows.reduce((s, r) => s + (parseFloat(r.total) || 0), 0);

/* ─────────────────── Print / PDF ─────────────────── */
const PrintArea = React.forwardRef(({ project, boqData, phase }, ref) => {
  const planRows  = boqData.planBOQ  || [];
  const finalRows = boqData.finalBOQ || [];

  const PrintTable = ({ rows, label }) => (
    <div className="boq-print-section">
      <h3 className="boq-print-section-title">{label}</h3>
      <table className="boq-print-table">
        <thead>
          <tr>
            <th>Category</th>
            <th>Code</th>
            <th>Unit</th>
            <th>Qty</th>
            <th>Unit Cost (₱)</th>
            <th>Total (₱)</th>
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr><td colSpan={6} style={{ textAlign: 'center', fontStyle: 'italic', color: '#9ca3af' }}>No items.</td></tr>
          ) : rows.map((r, i) => (
            <tr key={i}>
              <td>{r.product_category || '—'}</td>
              <td>{r.product_code || '—'}</td>
              <td style={{ textAlign: 'center' }}>{r.unit || '—'}</td>
              <td style={{ textAlign: 'center' }}>{r.qty || 0}</td>
              <td style={{ textAlign: 'right' }}>{fmt(r.unitCost)}</td>
              <td style={{ textAlign: 'right', fontWeight: 700 }}>{fmt(r.total)}</td>
            </tr>
          ))}
        </tbody>
        {rows.length > 0 && (
          <tfoot>
            <tr>
              <td colSpan={5} style={{ textAlign: 'right', fontWeight: 700 }}>Grand Total:</td>
              <td style={{ textAlign: 'right', fontWeight: 900 }}>{fmt(grandTotal(rows))}</td>
            </tr>
          </tfoot>
        )}
      </table>
    </div>
  );

  return (
    <div ref={ref} className="boq-print-area">
      {/* Header */}
      <div className="boq-print-header">
        <div>
          <h1 className="boq-print-title">Bill of Quantities</h1>
          <p className="boq-print-sub">{project?.name || 'Project'}</p>
        </div>
        <div className="boq-print-meta">
          <div><span>Client:</span> {project?.client || '—'}</div>
          <div><span>Date:</span> {new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        </div>
      </div>

      {/* Measurement comparison */}
      <div className="boq-print-measurements">
        <div className="boq-print-meas-col">
          <strong>Plan Measurement</strong>
          <div className="boq-print-sqm">{boqData.planSqm || '0.00'} sqm</div>
          <p>{boqData.planMeasurement || '—'}</p>
        </div>
        {phase === 'actual' && (
          <div className="boq-print-meas-col">
            <strong>Actual Site Measurement</strong>
            <div className="boq-print-sqm">{boqData.actualSqm || '0.00'} sqm</div>
            <p>{boqData.actualMeasurement || '—'}</p>
          </div>
        )}
      </div>

      {/* BOQ tables */}
      <PrintTable rows={planRows} label="Plan BOQ" />
      {phase === 'actual' && (
        <PrintTable rows={finalRows} label="Final BOQ (Actual)" />
      )}

      <div className="boq-print-footer">
        Generated by Project Management System &nbsp;|&nbsp; {new Date().toLocaleString('en-PH')}
      </div>
    </div>
  );
});

/* ─────────────────── Section divider ─────────────────── */
const PhaseDivider = ({ label }) => (
  <div className="boq-phase-divider">
    <span className="boq-phase-divider-label">{label}</span>
  </div>
);

/* ─────────────────── Measurement card ─────────────────── */
const MeasurementCard = ({ title, sqmValue, onSqmChange, notesValue, onNotesChange, readOnly, variant = 'gray' }) => (
  <div className={`pm-card-${variant} boq-meas-card`}>
    <label className="pm-label boq-meas-label">
      {title}
      <span className="boq-meas-unit">sqm</span>
    </label>
    <div className="boq-meas-row">
      <input
        type="number"
        min="0"
        step="0.01"
        value={sqmValue || ''}
        onChange={onSqmChange}
        readOnly={readOnly}
        className="pm-input boq-sqm-input"
        style={readOnly ? { background: 'var(--pm-bg-muted,#f3f4f6)', cursor: 'not-allowed' } : {}}
        placeholder="0.00"
      />
      <textarea
        value={notesValue || ''}
        onChange={onNotesChange}
        readOnly={readOnly}
        placeholder={readOnly ? 'No plan notes entered.' : 'Input measurement notes…'}
        className="pm-textarea boq-meas-notes"
        rows={2}
        style={readOnly ? { background: 'var(--pm-bg-muted,#f3f4f6)', cursor: 'not-allowed' } : {}}
      />
    </div>
  </div>
);

/* ─────────────────── Main component ─────────────────── */
const PhaseBoq = ({
  project,
  boqData,
  setBoqData,
  addBoqRow,
  removeBoqRow,
  handleBoqChange,
  onSubmitPlan,
  onSubmitActual,
  renderDocumentLink,
  phase = 'plan', // 'plan' | 'actual'
}) => {
  const printRef = useRef(null);

  /* Auto-populate finalBOQ from planBOQ when switching to actual phase */
  useEffect(() => {
    if (phase !== 'actual') return;
    const planRows  = boqData.planBOQ  || [];
    const finalRows = boqData.finalBOQ || [];
    if (planRows.length > 0 && finalRows.length === 0) {
      setBoqData(prev => ({ ...prev, finalBOQ: planRows.map(r => ({ ...r })) }));
    }
  }, [phase]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleExportPDF = () => {
    window.print();
  };

  const isActual = phase === 'actual';

  return (
    <div className="boq-phase-root">

      {/* Rejection banner */}
      {project?.rejection_notes && (
        <div className="pm-card-red">
          <h4 className="pm-title-md pm-label-red">🚨 REVISION REQUIRED FROM DEPT. HEAD</h4>
          <p className="pm-text-muted" style={{ margin: 0 }}>"{project.rejection_notes}"</p>
        </div>
      )}

      {/* Floor plan reference */}
      {renderDocumentLink?.('Floor Plan Reference', project?.floor_plan_image)}

      {/* ══ PLAN SECTION ══ */}
      <PhaseDivider label="Plan Phase" />

      <div style={{ opacity: isActual ? 0.75 : 1, pointerEvents: isActual ? 'none' : 'auto' }}>
        <MeasurementCard
          title="Plan Measurement Notes"
          sqmValue={boqData.planSqm}
          onSqmChange={e => setBoqData({ ...boqData, planSqm: e.target.value })}
          notesValue={boqData.planMeasurement}
          onNotesChange={e => setBoqData({ ...boqData, planMeasurement: e.target.value })}
          readOnly={isActual}
          variant="gray"
        />

        <BoqTable
          type="planBOQ"
          boqData={boqData}
          readOnly={isActual}
          onAdd={addBoqRow}
          onRemove={removeBoqRow}
          onChange={handleBoqChange}
        />
      </div>

      {/* Plan submit / export row */}
      {!isActual && (
        <div className="boq-action-row">
          <PrimaryButton variant="red" onClick={onSubmitPlan}>
            Save Plan Data &amp; Proceed to Site Visit
          </PrimaryButton>
          <button type="button" className="boq-export-btn" onClick={handleExportPDF}>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
              <line x1="12" y1="12" x2="12" y2="18"/>
              <line x1="9" y1="15" x2="15" y2="15"/>
            </svg>
            Export PDF
          </button>
        </div>
      )}

      {/* ══ ACTUAL SECTION (only shown in actual phase) ══ */}
      {isActual && (
        <>
          <PhaseDivider label="Actual Phase" />

          <div className="boq-measurements-row">
            <MeasurementCard
              title="Measurement Based on Plan"
              sqmValue={boqData.planSqm}
              notesValue={boqData.planMeasurement}
              readOnly={true}
              variant="gray"
            />
            <MeasurementCard
              title="Actual Site Measurement"
              sqmValue={boqData.actualSqm}
              onSqmChange={e => setBoqData({ ...boqData, actualSqm: e.target.value })}
              notesValue={boqData.actualMeasurement}
              onNotesChange={e => setBoqData({ ...boqData, actualMeasurement: e.target.value })}
              readOnly={false}
              variant="cream"
            />
          </div>

          {/* Final / Actual BOQ — editable, pre-filled from plan */}
          <BoqTable
            type="finalBOQ"
            boqData={boqData}
            readOnly={false}
            onAdd={addBoqRow}
            onRemove={removeBoqRow}
            onChange={handleBoqChange}
          />

          <div className="boq-action-row">
            <PrimaryButton variant="red" onClick={onSubmitActual}>
              Submit Final BOQ for Approval
            </PrimaryButton>
            <button type="button" className="boq-export-btn" onClick={handleExportPDF}>
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="12" y1="12" x2="12" y2="18"/>
                <line x1="9" y1="15" x2="15" y2="15"/>
              </svg>
              Export PDF
            </button>
          </div>
        </>
      )}

      {/* ══ Hidden print area ══ */}
      <PrintArea ref={printRef} project={project} boqData={boqData} phase={phase} />
    </div>
  );
};

export default PhaseBoq;
